spring:
  application:
    name: proResponse
  profiles:
    include:
    - private

springdoc:
  swagger-ui:
    path: /ui.html
    
server:
  port: 8080
    
 
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.kh.even.back.*.model.vo, com.kh.even.back.*.model.dto 
  mapper-locations: classpath:mapper/**/*.xml
      